### ISSUE TITLE
Ore dictionary use as suggestion for next update

### ISSUE THREAD

**Issue by alxcool** [Corail31/recycler#11]
Hello! I really enjoy playing this mod so I would like to share a suggestion for next update. I use the old Minecraft launcher with forge 2603 as Profile for Solo-Player on a Windows 7 64-bit.

I encountered a small compatibility problem between game changes.
Recycler and Inventory-Pets.
https://minecraft.curseforge.com/projects/inventory-pets
They use the same recipe ingredient for two different results.
Ex : 
Diamond to diamond_fragment * 9
or 
Diamond to nugget_diamond * 9

Looking for solutions, I found a mod that allows to modify the recipes:
CraftTweaker (which contains MineTweaker3).
https://minecraft.curseforge.com/projects/crafttweaker

So, here is a solution in a language that may not be universal but should be simple to use (provided I did not make a writing error):

ore:nuggetDiamond.add (<recycler: diamond_fragment>);
recipes.remove (<recycler: diamond_disk>);
recipes.addShaped (<recycler: diamond_disk_alt>, [[null, ore:nuggetDiamond, null],
[ore:nuggetDiamond, ore:ingotIron, ore:nuggetDiamond], [null, ore:nuggetDiamond, null]]);

So, I added an entry to the "Ore Dictionary" suggested by Inventory-Pets because according to Craftweaker, Recycler does not use any at the moment. What do you think?

**Comment by Corail31** [comment]
Hi Alxcool,
Good idea and thanks for the interest to my mod :)
So, the idea if i correctly understood :
- add the diamond fragment in the ore dictionary as "nuggetDiamond"
- adapt the recipes to use the ore names

**Comment by alxcool** [comment]
Yes that's exactly it! Thk for your fast reply.

**Comment by Corail31** [comment]
You're welcome ;)
