### ISSUE TITLE
Config option about losses can generate a divide by zero

### ISSUE THREAD

**Issue by alxcool** [Corail31/recycler#12]
Single player 1.12.2
Forge 2705
recycler-3.0.0-1.12
twilightforest-1.12.2-3.7.424-universal

Hi! There seem to be an error in one of my recipes, probably one of mine, as it create a
"java.lang.ArithmeticException: / by zero"
I was including a few items from twilight forest, when this issue happen. The only left item in the recycler right now is a minecraft:iron_bars. And the crash look to be stuck on a loop.

Here some more info : 
https://paste.dimdev.org/ijukewuked.mccrash
https://paste.dimdev.org/puhivoqema.mccrash
[latest.log](https://github.com/Corail31/recycler/files/2280634/latest.log)
Config file on OneDrive, since not supported on github.
https://1drv.ms/u/s!Aid4Qdg_TbongxWC8B-bfduHcnre
https://1drv.ms/u/s!Aid4Qdg_TbongxaipTCckys1z2kG

**Comment by alxcool** [comment]
Used aroma backup, then I understand more what happened... I've asked to recycle a damaged item, a twilightforest:steelleaf_boots but the damage point was too high, the result would usually end with the machine who refuse to perform such action, because it will end up with no resource at all, but somehow its like if it tried to do it even so... Note this is an item who earn an enchantment on creation, but this one lost it because I'v repair it in my inventory with the same item. So both my mistake, you could close this after you read it, or should I?

**Comment by Corail31** [comment]
Hi alxcool,
Not sure to understand all but you seem to have solved it, so... :)

**Comment by alxcool** [comment]
Sorry to reopen this... I kinda have more information. This minor error, who become a crash, when occurring on a loop, happen when I ask recycler to perform an action about a recipe who return, or use very few items in return; probably an attempt to use (converted_grind.json).

Both stick to plank (2 sticks = 1 plank), or iron bar to iron nugget (Probably a recipe of mine; 1 bar = 3 nuggets) create this issue. But, this is not a recurrent error. So I guess it depend on a second trigger, the one about "config:percent loss" that I've set to 15%. So in average, 15% of the time, the machine try to give me back half of, or a quarter of a plank or 3/4 of a iron nugget... that may be rounded to 0... Then, it end up with this error code : 
"java.lang.ArithmeticException: / by zero"

I may not be right or good to explain this issue. But could you check if its possible to replace a variable in the 2 previous described function? About me the result is rounded to 0 because the variable is set to only use integer. If there is a way to use, as variable type, a "reel", instead, about me this could solve the problem. 

Note create a crash loop when there is a stack of stick, or a stack of iron bar, in the machine on "auto recycle" mode, until the request is complete. Once manually canceled, or the task is complete, game could be recovered without the need of a backup.

**Comment by Corail31** [comment]
I'll make a check on it.
As my source showed it, i stopped the previous update on the recycling code that i always need to clean :)

**Comment by Corail31** [comment]
Can you set the Config option "chance_loss" to 0 until the fix ? ;)
Because the divide by zero is coming from this and i'll patch it in some times

**Comment by Corail31** [comment]
So, the trouble is always the time (i'm alone to mod all my projects), so in general, i have a todolist for all the coming changes of my mods (and i have done a lot for recycler in the v3 of recycler)
a) for the first point, it's up to you to update the default existing recipes
b) it's not how recycler work (and i think this kind of 'residual' storage is a bad idea for performance)
c) the slot "book" is a coming change (but i have no date for the next change of recycler)
