### ISSUE TITLE
damaged items aren't correctly recycled

### ISSUE THREAD

**Issue by zortag** [Corail31/recycler#13]
i started using the mod with the version 1.5.0-1.12.2 and it worked as expected. i used in another modpack the version 3.1.0-1.12.2 and the recycler no longer extract the enchantment from the items as before (vanilla and non-vanilla items). maybe a conflict with something or i did something wrong? i checked the config file and the enchant extraction is activated, really i not changed the config. i only added some recipe with the command. i also searched a solution on the web without luck, so i'm writing here

**Comment by zortag** [comment]
i discovered now also damaged items don't works. instead giving the parts of ingredients a damaged item simply disappear

**Comment by Corail31** [comment]
I made lots of changes in V3, but a part is to finish to display the enchantments on the grid, but normally they're extracted any way. I'll make checks about it. But have you tried without your custom recipes first ?

**Comment by Corail31** [comment]
So i made the checks :
- enchantments are correctly recycled
-> actually, the recycler remembers the last recipe, to avoid to recalculate the result, that's why enchantments aren't for now shown on the crafting grid but it works any way.
- damaged items seems to be bugued, i need to fix it

**Comment by Corail31** [comment]
![image](https://user-images.githubusercontent.com/17954109/44950904-1609e300-ae55-11e8-8a94-ed6f2e2507a6.png)
I suppose you want this, and i'm finishing it :)

**Comment by Corail31** [comment]
fixed in 3.2.0 : now it's up to you to make the tests if it works as expected :)

**Comment by zortag** [comment]
you're totally right, sorry i had no time to answer before now
