### ISSUE TITLE
java.lang.nullPointerException

### ISSUE THREAD

**Issue by DatrixTHLK** [Corail31/recycler#14]
Hi Corail,

Recently, minecraft crashed and your mod came up as the culprit for nullpointerException. I was trying to recycle some armor, tools and weapons when the game suddenly froze up.

Minecraft 1.12.2
Forge: 14.23.4.2765
Corail Recycler: 3.2.0
Crash Log: https://paste.dimdev.org/noqoyoduha.mccrash

**Comment by Corail31** [comment]
Hi Datrix,
Thanks for you report, i'll prevent the issue :) (probably today)

**Comment by DatrixTHLK** [comment]
Thanks for the response time and the fix

**Comment by Corail31** [comment]
Can You test if it's ok with this version ? [Here](https://cdn.discordapp.com/attachments/294828573053812736/496560928259571723/recycler-3.2.1-1.12.jar)

**Comment by DatrixTHLK** [comment]
It seems to work fine now that I generated a new world. i'll let you know what happens if anything does.

**Comment by Corail31** [comment]
i had one chance on 2 on the first try :)

**Comment by DatrixTHLK** [comment]
I figured as much. Thanks atleast for trying to fix the issue
