### ISSUE TITLE
Server Crash when using recycler auto mode

### ISSUE THREAD

**Issue by boosterdev** [Corail31/recycler#16]
Not sure why or how it happends but apparently when user use auto mode, it crashes.

[crash-2018-10-15_12.56.44-server.txt](https://gist.githubusercontent.com/boosterdev/0f92f509a6c806baac7240334a727927/raw/d7ef6d4d03a5967ece06b0f45c7e1a453e101a59/gistfile1.txt)

its non recoverable crash, mod needs to be removed will the world continue.

**Comment by Corail31** [comment]
I think that you have set the config to 0 tick for auto-recycle (time_to_recycle), and it requires a positive value above 0, i'll set a minimum in the coming version.
