### ISSUE TITLE
[Popular mods config files]

### ISSUE THREAD

**Issue by alxcool** [Corail31/recycler#17]
Hi! I would like to share some already built recycler's config files, about a few popular mods, to be used in addition with this mod. How should I do it, and where should I share this idea?

I was wondering if I should open a curseforge project who offer some downloads.
What are your though on my first draft? I've tested every lines and fixed possible mistakes ;)
[biomeoplenty2402.txt](https://github.com/Corail31/recycler/files/2536578/biomeoplenty2402.txt)
[ConvertedGrid_biomeoplenty2402.txt](https://github.com/Corail31/recycler/files/2536579/ConvertedGrid_biomeoplenty2402.txt)
I could as example suggest players where and how to cut and paste theses lines inside their config files.

I hope I could help you develop this mod, let me know If I could be of any help ;)

**Comment by Corail31** [comment]
Hi Alxcool, that's a neat idea for people knowning how to use them :)
They could be in the config folder, with a name like template_biomeoplenty.

**Comment by alxcool** [comment]
Din't tough about making the process automatic, I will try! While waiting, here an another one, I've took time to build and test today! 
[tconstruct11106.txt](https://github.com/Corail31/recycler/files/2540528/tconstruct11106.txt)

**Comment by Corail31** [comment]
I could put the files in the recycler folder as template, as finally mods can change them over time, and it would take time to keep them update where the command can generate the list very fast too.

**Comment by alxcool** [comment]
Your right as it may take lots of time too
[natura43262.txt](https://github.com/Corail31/recycler/files/2550671/natura43262.txt)
, I'l see what I can do on my side too. While waiting...
