### ISSUE TITLE
Tooltip for iron nuggets is incorrect and unneeded

### ISSUE THREAD

**Issue by MentalMouse** [Corail31/recycler#2]
It says the iron nuggets can be crafted into Diamonds.  (Um, nope.)  And frankly, the tooltip is unneeded; gold nuggets provide sufficient example.

**Comment by Corail31** [comment]
This is just a wrong translate in the lang file :) It'll be changed on next release.

**Comment by Corail31** [comment]
nugget description tooltip 'll be removed byt the way.
