### ISSUE TITLE
So much Diamonds from Enchantet Items intended?

### ISSUE THREAD

**Issue by 4Magma** [Corail31/recycler#5]
Processing of enchantet Items gives multiple diamond nuggets. 
For each enchantet Book even 7 diamonds.
I can take a enchanted book again and again to get diamonds.

suggestion:
- no diamond (or nuggets) as output
- books are needed to as target for extracted enchantments 
  (extra Slot, in auto mode all books go into, books not recyclable)
- enchanted bows, rods, stone|wood|leather armor|tools|weapon produce no extra material
- enchanted iron|gold|diamond items produce additionally their respectively nuggets
- enchanted books with one enchantment fall through
- enchanted books with multiple enchantments were "splitted"

**Comment by Corail31** [comment]
It's not intended, so i'll have a look on it.
But are you sure if you click the recycle action to really have the diamonds ? because visual in the result are not the result of recycle action .
